
export const CATEGORIES = [
    { id: 'positive', label: 'Positive', emoji: '✨' },
    { id: 'life', label: 'Life', emoji: '🌱' },
    { id: 'motivation', label: 'Motivation', emoji: '🔥' },
    { id: 'study', label: 'Study', emoji: '📚' },
    { id: 'love', label: 'Love', emoji: '❤️' },
    { id: 'wisdom', label: 'Wisdom', emoji: '🦉' },
    { id: 'success', label: 'Success', emoji: '🏆' },
    { id: 'happiness', label: 'Happiness', emoji: '😊' },
    { id: 'sad', label: 'Sad', emoji: '🌧️' },
    { id: 'faith', label: 'Faith', emoji: '🙏' },
    { id: 'affirmations', label: 'Affirmations', emoji: '🧘' },
    { id: 'funny', label: 'Funny', emoji: '😂' },
    { id: 'friendship', label: 'Friendship', emoji: '🤝' },
    { id: 'gym', label: 'Gym', emoji: '💪' },
    { id: 'morning', label: 'Morning', emoji: '☀️' },
    { id: 'night', label: 'Night', emoji: '🌙' },
    { id: 'healing', label: 'Healing', emoji: '❤️‍🩹' },
    { id: 'nature', label: 'Nature', emoji: '🌿' },
    { id: 'calm', label: 'Calm', emoji: '🌊' },
    { id: 'books', label: 'Book', emoji: '📖' },
    { id: 'aesthetic', label: 'Aesthetic', emoji: '🎨' },
    { id: 'minimal', label: 'Minimal', emoji: '⚪' },
    { id: 'phone', label: 'Phone', emoji: '📱' },
    { id: 'dark', label: 'Dark', emoji: '🌑' },
    { id: 'vintage', label: 'Vintage', emoji: '📺' },
];
